from .luokat import Humanoidi
from .luokat import Pelaaja
from .luokat import Esine
from .luokat import Miekka
from .luokat import Huone
from .luokat import Kauppa
from .luokat import Luola
from .funktiot import tallenna
from .funktiot import reppu
from .funktiot import tavarat
from .funktiot import lyönti